// "parentDocId","docId","DateAdded","ContactDate","ContactLocation","ContactType","ContactNotes","FosterKinshipEmployee","TimeSpentMinutes"

export const PrimaryKinshipCaregiverContact = {
    title:'Contacts',
    toolbarTitle:"Contacts With Caregiver", 
    collectionId:"PrimaryKinshipCaregiverContact",
    icon:"phone",
    addIcon:"phone_forwarded",
    addButtonText:"Add Contact",
    evalFunctions:{
      breadCrumb:'"Contact - " + entityId',
      subEntityListDisplayText:'(entityFormFields.ContactDate||"") + " - " + (entityFormFields.ContactType||"")',
    },
    onDelete:{
      confirmMessage:"Are you sure you want to delete this contact from the primary kinship caregiver?",
      route:"/dashboard",
    },
    formFields:[
      {
        fieldType:'text',
        fieldName:"DateAdded",
        fieldLabel:"Date Added",
        disabled:true,
      },
      {
        fieldType:'Date',
        fieldName:"ContactDate",
        fieldLabel:"Contact Date",
      },
      {
        fieldType:'select',
        fieldName:"ContactLocation",
        fieldLabel:"Contact Location",
        fieldItems:[
            "Phone",
            "Email",
            "Mail",
            "Office",
            "Field",
            "Home",
            "Facebook Group",
        ],
      },
      {
        fieldType:'select',
        fieldName:"ContactType",
        fieldLabel:"Contact Type",
        fieldItems:[
          "Car Seat Check",
          "Car Seat Education Class",
          "Case Plan Referral",
          "Case Work/Research",
          "Copy Service",
          "CPLC Parenting Class",
          "CPR/First Aid Class",
          "Death Benefits",
          "DFS Info Session",
          "Emergency Resource",
          "Emotional Support",
          "Energy Assistance Application Assistance",
          "Family Event",
          "Follow Up Check- Family Advocacy",
          "Helpline- Info only",
          "Intake",
          "Kinship Licensing Class #5",
          "Licensing Application Assistance",
          "Medicaid",
          "Notary",
          "Permanency Session",
          "Pre-Test",
          "Post-Test",
          "Resource Locator Tool",
          "SNAP",
          "Support Group",
          "TANF Application Session",
          "QPI Training",       
        ],
      },
      {
        fieldType:'text',
        fieldName:"ContactNotes",
        fieldLabel:"Contact Notes",
      },
      {
        fieldType:'select',
        fieldName:"FosterKinshipEmployee",
        fieldLabel:"FosterKinship Employee",
        fieldItems:[
          "Berenice Blas",
          "Alison Caliendo",
          "Anntesha Chesterton",
          "Leah Dods",
          "Nani Garrett",
          "Michelle Pulido",
          "Sandy Vargas",
        ],
      },
      {
        fieldType:'text',
        fieldName:"TimeSpentMinutes",
        fieldLabel:"Time Spent Minutes",
      },
    ],
  }
